-- Governed synthetic incident workflow.  It deliberately has no notification,
-- escalation execution, work-order, autonomous control, PLC, or RTU pathway.
CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TYPE audit_event_resource ADD VALUE IF NOT EXISTS 'incident';
ALTER TYPE audit_event_resource ADD VALUE IF NOT EXISTS 'escalation_policy';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'escalation_policy.created';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'escalation_policy_version.requested';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'escalation_policy_version.approved';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'incident.created';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'incident.alarm_linked';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'incident.acknowledged';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'incident.investigating';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'incident.assigned';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'incident.commented';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'incident.corrective_action';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'incident.resolved';
ALTER TYPE audit_event_action ADD VALUE IF NOT EXISTS 'incident.closed';

CREATE TABLE IF NOT EXISTS escalation_policies (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), territory_id uuid NOT NULL REFERENCES territories(id),
 event_type text NOT NULL REFERENCES alarm_catalog_event_types(code), severity text NOT NULL CHECK(severity IN('information','advisory','warning','critical')),
 title text NOT NULL CHECK(btrim(title)<>''), provenance text NOT NULL CHECK(btrim(provenance)<>''), data_classification record_data_classification NOT NULL DEFAULT 'synthetic',
 created_by_user_id uuid NOT NULL REFERENCES identity_users(id), creation_reason text NOT NULL CHECK(btrim(creation_reason)<>''), created_request_id text NOT NULL CHECK(btrim(created_request_id)<>''), created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 CHECK(data_classification='synthetic'), UNIQUE(organization_id,territory_id,event_type,severity)
);
CREATE TABLE IF NOT EXISTS escalation_policy_versions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), policy_id uuid NOT NULL REFERENCES escalation_policies(id), version integer NOT NULL CHECK(version>0), status text NOT NULL DEFAULT 'requested' CHECK(status IN('requested','approved')),
 effective_from timestamptz NOT NULL, effective_until timestamptz NOT NULL, tier integer NOT NULL CHECK(tier BETWEEN 1 AND 9), procedure text NOT NULL CHECK(btrim(procedure)<>''),
 acknowledgement_target_microseconds bigint NOT NULL CHECK(acknowledgement_target_microseconds BETWEEN 1 AND 31536000000000), resolution_target_microseconds bigint NOT NULL CHECK(resolution_target_microseconds BETWEEN 1 AND 31536000000000),
 requested_by_user_id uuid NOT NULL REFERENCES identity_users(id), requested_at timestamptz NOT NULL DEFAULT clock_timestamp(), request_reason text NOT NULL CHECK(btrim(request_reason)<>''), requested_request_id text NOT NULL CHECK(btrim(requested_request_id)<>''),
 approved_by_user_id uuid REFERENCES identity_users(id), approved_at timestamptz, approval_reason text, approved_request_id text, UNIQUE(policy_id,version), CHECK(effective_until>effective_from),
 CHECK((status='requested' AND approved_by_user_id IS NULL AND approved_at IS NULL AND approval_reason IS NULL AND approved_request_id IS NULL) OR (status='approved' AND approved_by_user_id IS NOT NULL AND approved_at IS NOT NULL AND approved_by_user_id<>requested_by_user_id AND approval_reason IS NOT NULL AND approved_request_id IS NOT NULL)),
 EXCLUDE USING gist(policy_id WITH =,tstzrange(effective_from,effective_until,'[)') WITH &&) WHERE(status='approved')
);
CREATE TABLE IF NOT EXISTS incidents (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), territory_id uuid NOT NULL REFERENCES territories(id), primary_alarm_id uuid NOT NULL REFERENCES alarms(id),
 status text NOT NULL DEFAULT 'open' CHECK(status IN('open','acknowledged','investigating','resolved','closed')), assigned_user_id uuid REFERENCES identity_users(id),
 acknowledged_by_user_id uuid REFERENCES identity_users(id), acknowledged_at timestamptz, resolved_at timestamptz, closed_at timestamptz,
 escalation_policy_id uuid REFERENCES escalation_policies(id), escalation_policy_version_id uuid REFERENCES escalation_policy_versions(id), escalation_tier integer, escalation_procedure text,
 acknowledgement_target_microseconds bigint, resolution_target_microseconds bigint, acknowledgement_due_at timestamptz, resolution_due_at timestamptz,
 created_by_user_id uuid NOT NULL REFERENCES identity_users(id), creation_reason text NOT NULL CHECK(btrim(creation_reason)<>''), created_request_id text NOT NULL CHECK(btrim(created_request_id)<>''), created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 data_classification record_data_classification NOT NULL DEFAULT 'synthetic', official_compliance_eligible boolean NOT NULL DEFAULT false,
 CHECK(data_classification='synthetic' AND NOT official_compliance_eligible),
 CHECK((acknowledged_by_user_id IS NULL AND acknowledged_at IS NULL) OR(acknowledged_by_user_id IS NOT NULL AND acknowledged_at IS NOT NULL)),
 CHECK((escalation_policy_id IS NULL AND escalation_policy_version_id IS NULL AND escalation_tier IS NULL AND escalation_procedure IS NULL AND acknowledgement_target_microseconds IS NULL AND resolution_target_microseconds IS NULL AND acknowledgement_due_at IS NULL AND resolution_due_at IS NULL) OR (escalation_policy_id IS NOT NULL AND escalation_policy_version_id IS NOT NULL AND escalation_tier IS NOT NULL AND escalation_procedure IS NOT NULL AND acknowledgement_target_microseconds IS NOT NULL AND resolution_target_microseconds IS NOT NULL AND acknowledgement_due_at IS NOT NULL AND resolution_due_at IS NOT NULL))
);
CREATE TABLE IF NOT EXISTS incident_alarm_links (
 incident_id uuid NOT NULL REFERENCES incidents(id), alarm_id uuid NOT NULL REFERENCES alarms(id), linked_by_user_id uuid NOT NULL REFERENCES identity_users(id), link_reason text NOT NULL CHECK(btrim(link_reason)<>''), linked_request_id text NOT NULL CHECK(btrim(linked_request_id)<>''), linked_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(incident_id,alarm_id), UNIQUE(alarm_id)
);
CREATE TABLE IF NOT EXISTS incident_timeline (
 incident_id uuid NOT NULL REFERENCES incidents(id), sequence integer NOT NULL CHECK(sequence>0), kind text NOT NULL CHECK(kind IN('created','alarm_linked','acknowledged','investigating','assigned','commented','corrective_action','resolved','closed')), actor_user_id uuid NOT NULL REFERENCES identity_users(id), reason text NOT NULL CHECK(btrim(reason)<>''), body text, assignee_user_id uuid REFERENCES identity_users(id), alarm_id uuid REFERENCES alarms(id), request_id text NOT NULL CHECK(btrim(request_id)<>''), occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(incident_id,sequence), UNIQUE(incident_id,request_id)
);
ALTER TABLE incident_timeline ADD COLUMN IF NOT EXISTS alarm_id uuid REFERENCES alarms(id);
CREATE UNIQUE INDEX IF NOT EXISTS incident_timeline_single_lifecycle_uq ON incident_timeline(incident_id,kind) WHERE kind IN('created','acknowledged','investigating','resolved','closed');
CREATE INDEX IF NOT EXISTS incidents_territory_idx ON incidents(territory_id,created_at DESC,id DESC);

CREATE OR REPLACE FUNCTION incident_actor_may_write(actor_id uuid,target_org uuid,target_territory uuid,evaluated_at timestamptz) RETURNS boolean LANGUAGE sql STABLE AS $$
 WITH RECURSIVE ancestors AS(SELECT id,parent_territory_id FROM territories WHERE id=target_territory AND organization_id=target_org UNION ALL SELECT t.id,t.parent_territory_id FROM territories t JOIN ancestors a ON a.parent_territory_id=t.id WHERE t.organization_id=target_org),
 actor AS(SELECT id,organization_id FROM identity_users WHERE id=actor_id AND is_active)
 SELECT EXISTS(SELECT 1 FROM user_role_grants g CROSS JOIN actor WHERE g.user_id=actor_id AND g.cancelled_at IS NULL AND g.effective_from<=evaluated_at AND(g.effective_until IS NULL OR g.effective_until>evaluated_at) AND ((g.role='system_admin' AND g.organization_id=actor.organization_id AND g.scope='system' AND g.territory_id IS NULL) OR(g.organization_id=target_org AND actor.organization_id=target_org AND g.role='national_admin' AND g.scope='national' AND g.territory_id IS NULL) OR(g.organization_id=target_org AND actor.organization_id=target_org AND g.role IN('regional_director','basin_dispatcher','district_operator','maintenance_engineer') AND g.scope='territory' AND EXISTS(SELECT 1 FROM ancestors WHERE id=g.territory_id))))
$$;
CREATE OR REPLACE FUNCTION incident_actor_may_approve(actor_id uuid,target_org uuid,target_territory uuid,evaluated_at timestamptz) RETURNS boolean LANGUAGE sql STABLE AS $$
 WITH RECURSIVE ancestors AS(SELECT id,parent_territory_id FROM territories WHERE id=target_territory AND organization_id=target_org UNION ALL SELECT t.id,t.parent_territory_id FROM territories t JOIN ancestors a ON a.parent_territory_id=t.id WHERE t.organization_id=target_org),
 actor AS(SELECT id,organization_id FROM identity_users WHERE id=actor_id AND is_active)
 SELECT EXISTS(SELECT 1 FROM user_role_grants g CROSS JOIN actor WHERE g.user_id=actor_id AND g.cancelled_at IS NULL AND g.effective_from<=evaluated_at AND(g.effective_until IS NULL OR g.effective_until>evaluated_at) AND ((g.role='system_admin' AND g.organization_id=actor.organization_id AND g.scope='system' AND g.territory_id IS NULL) OR(g.organization_id=target_org AND actor.organization_id=target_org AND g.role='national_admin' AND g.scope='national' AND g.territory_id IS NULL) OR(g.organization_id=target_org AND actor.organization_id=target_org AND g.role='regional_director' AND g.scope='territory' AND EXISTS(SELECT 1 FROM ancestors WHERE id=g.territory_id))))
$$;
CREATE OR REPLACE FUNCTION escalation_policy_validate() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.created_at:=clock_timestamp(); IF NOT EXISTS(SELECT 1 FROM territories WHERE id=NEW.territory_id AND organization_id=NEW.organization_id) OR NOT incident_actor_may_write(NEW.created_by_user_id,NEW.organization_id,NEW.territory_id,NEW.created_at) THEN RAISE EXCEPTION 'escalation policy author or scope is invalid' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION escalation_policy_version_validate() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE p escalation_policies%ROWTYPE; expected integer; BEGIN PERFORM pg_advisory_xact_lock(hashtext(NEW.policy_id::text)); SELECT * INTO STRICT p FROM escalation_policies WHERE id=NEW.policy_id; SELECT COALESCE(max(version),0)+1 INTO expected FROM escalation_policy_versions WHERE policy_id=NEW.policy_id; NEW.version:=expected;NEW.status:='requested';NEW.requested_at:=clock_timestamp(); IF NEW.approved_by_user_id IS NOT NULL OR NEW.approved_at IS NOT NULL OR NEW.approval_reason IS NOT NULL OR NEW.approved_request_id IS NOT NULL OR NOT incident_actor_may_write(NEW.requested_by_user_id,p.organization_id,p.territory_id,NEW.requested_at) THEN RAISE EXCEPTION 'escalation policy version request is invalid' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION escalation_policy_version_update_validate() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE p escalation_policies%ROWTYPE; BEGIN IF OLD.status='requested' AND NEW.status='approved' AND NEW.id=OLD.id AND NEW.policy_id=OLD.policy_id AND NEW.version=OLD.version AND NEW.effective_from=OLD.effective_from AND NEW.effective_until=OLD.effective_until AND NEW.tier=OLD.tier AND NEW.procedure=OLD.procedure AND NEW.acknowledgement_target_microseconds=OLD.acknowledgement_target_microseconds AND NEW.resolution_target_microseconds=OLD.resolution_target_microseconds AND NEW.requested_by_user_id=OLD.requested_by_user_id AND NEW.requested_at=OLD.requested_at AND NEW.request_reason=OLD.request_reason AND NEW.requested_request_id=OLD.requested_request_id AND NEW.approved_by_user_id IS NOT NULL AND NEW.approved_by_user_id<>OLD.requested_by_user_id AND NEW.approval_reason IS NOT NULL AND NEW.approved_request_id IS NOT NULL THEN SELECT * INTO STRICT p FROM escalation_policies WHERE id=NEW.policy_id;NEW.approved_at:=clock_timestamp();IF NOT incident_actor_may_approve(NEW.approved_by_user_id,p.organization_id,p.territory_id,NEW.approved_at) THEN RAISE EXCEPTION 'escalation policy approval is invalid' USING ERRCODE='23514';END IF;RETURN NEW;END IF;RAISE EXCEPTION 'escalation policy versions are immutable' USING ERRCODE='23514';END $$;
CREATE OR REPLACE FUNCTION incident_timeline_validate() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE expected integer; i incidents%ROWTYPE; context_actor uuid:=NULLIF(current_setting('isuv.incident_actor_id',true),'')::uuid;context_reason text:=NULLIF(current_setting('isuv.incident_reason',true),'');context_request text:=NULLIF(current_setting('isuv.incident_request_id',true),''); BEGIN PERFORM pg_advisory_xact_lock(hashtext(NEW.incident_id::text));SELECT * INTO STRICT i FROM incidents WHERE id=NEW.incident_id;SELECT COALESCE(max(sequence),0)+1 INTO expected FROM incident_timeline WHERE incident_id=NEW.incident_id;NEW.sequence:=expected;NEW.occurred_at:=clock_timestamp();IF context_actor IS NULL OR context_reason IS NULL OR context_request IS NULL OR NEW.actor_user_id<>context_actor OR NEW.reason<>context_reason OR NEW.request_id<>context_request OR NOT incident_actor_may_write(NEW.actor_user_id,i.organization_id,i.territory_id,NEW.occurred_at) THEN RAISE EXCEPTION 'incident timeline provenance is invalid' USING ERRCODE='23514';END IF;IF (NEW.kind='created' AND (expected<>1 OR i.status<>'open' OR NEW.actor_user_id<>i.created_by_user_id)) OR (NEW.kind='alarm_linked' AND (i.status IN('resolved','closed') OR NEW.alarm_id IS NULL OR NOT EXISTS(SELECT 1 FROM incident_alarm_links link WHERE link.incident_id=NEW.incident_id AND link.alarm_id=NEW.alarm_id AND link.linked_by_user_id=NEW.actor_user_id AND link.link_reason=NEW.reason AND link.linked_request_id=NEW.request_id))) OR (NEW.kind='acknowledged' AND (i.status<>'acknowledged' OR NEW.actor_user_id<>i.acknowledged_by_user_id)) OR (NEW.kind='investigating' AND i.status<>'investigating') OR (NEW.kind='assigned' AND (i.status='closed' OR NEW.assignee_user_id IS DISTINCT FROM i.assigned_user_id)) OR (NEW.kind IN('commented','corrective_action') AND i.status='closed') OR (NEW.kind='resolved' AND i.status<>'resolved') OR (NEW.kind='closed' AND i.status<>'closed') OR (NEW.kind<>'alarm_linked' AND NEW.alarm_id IS NOT NULL) THEN RAISE EXCEPTION 'incident timeline state is invalid' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE OR REPLACE FUNCTION incident_validate() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE a alarms%ROWTYPE; p escalation_policies%ROWTYPE; v escalation_policy_versions%ROWTYPE; BEGIN PERFORM pg_advisory_xact_lock(hashtext(NEW.primary_alarm_id::text));SELECT * INTO STRICT a FROM alarms WHERE id=NEW.primary_alarm_id;NEW.created_at:=clock_timestamp(); IF NEW.status<>'open' OR NEW.assigned_user_id IS NOT NULL OR NEW.acknowledged_by_user_id IS NOT NULL OR NEW.acknowledged_at IS NOT NULL OR NEW.resolved_at IS NOT NULL OR NEW.closed_at IS NOT NULL OR NEW.escalation_policy_id IS NOT NULL OR NEW.escalation_policy_version_id IS NOT NULL OR NEW.escalation_tier IS NOT NULL OR NEW.escalation_procedure IS NOT NULL OR NEW.acknowledgement_target_microseconds IS NOT NULL OR NEW.resolution_target_microseconds IS NOT NULL OR NEW.acknowledgement_due_at IS NOT NULL OR NEW.resolution_due_at IS NOT NULL OR a.organization_id<>NEW.organization_id OR a.territory_id<>NEW.territory_id OR NOT incident_actor_may_write(NEW.created_by_user_id,NEW.organization_id,NEW.territory_id,NEW.created_at) THEN RAISE EXCEPTION 'incident alarm, initial state, author, or scope is invalid' USING ERRCODE='23514';END IF;SELECT policy.* INTO p FROM escalation_policies policy JOIN escalation_policy_versions version_row ON version_row.policy_id=policy.id WHERE policy.organization_id=a.organization_id AND policy.territory_id=a.territory_id AND policy.event_type=a.event_type AND policy.severity=a.severity AND version_row.status='approved' AND version_row.effective_from<=NEW.created_at AND version_row.effective_until>NEW.created_at AND version_row.approved_at<=NEW.created_at ORDER BY version_row.version DESC LIMIT 1;IF FOUND THEN SELECT version_row.* INTO STRICT v FROM escalation_policy_versions version_row WHERE version_row.policy_id=p.id AND version_row.status='approved' AND version_row.effective_from<=NEW.created_at AND version_row.effective_until>NEW.created_at AND version_row.approved_at<=NEW.created_at ORDER BY version_row.version DESC LIMIT 1;NEW.escalation_policy_id:=p.id;NEW.escalation_policy_version_id:=v.id;NEW.escalation_tier:=v.tier;NEW.escalation_procedure:=v.procedure;NEW.acknowledgement_target_microseconds:=v.acknowledgement_target_microseconds;NEW.resolution_target_microseconds:=v.resolution_target_microseconds;NEW.acknowledgement_due_at:=NEW.created_at+(v.acknowledgement_target_microseconds*interval '1 microsecond');NEW.resolution_due_at:=NEW.created_at+(v.resolution_target_microseconds*interval '1 microsecond');END IF;RETURN NEW;END $$;
CREATE OR REPLACE FUNCTION incident_update_validate() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE all_cleared boolean; actor_id uuid:=NULLIF(current_setting('isuv.incident_actor_id',true),'')::uuid;
BEGIN
 IF actor_id IS NULL OR NOT incident_actor_may_write(actor_id,OLD.organization_id,OLD.territory_id,clock_timestamp()) THEN RAISE EXCEPTION 'incident actor is unauthorized' USING ERRCODE='23514';END IF;
 IF NEW.id<>OLD.id OR NEW.organization_id<>OLD.organization_id OR NEW.territory_id<>OLD.territory_id OR NEW.primary_alarm_id<>OLD.primary_alarm_id OR NEW.created_by_user_id<>OLD.created_by_user_id OR NEW.created_at<>OLD.created_at OR NEW.creation_reason<>OLD.creation_reason OR NEW.created_request_id<>OLD.created_request_id OR NEW.data_classification<>OLD.data_classification OR NEW.official_compliance_eligible<>OLD.official_compliance_eligible OR NEW.escalation_policy_id IS DISTINCT FROM OLD.escalation_policy_id OR NEW.escalation_policy_version_id IS DISTINCT FROM OLD.escalation_policy_version_id OR NEW.escalation_tier IS DISTINCT FROM OLD.escalation_tier OR NEW.escalation_procedure IS DISTINCT FROM OLD.escalation_procedure OR NEW.acknowledgement_target_microseconds IS DISTINCT FROM OLD.acknowledgement_target_microseconds OR NEW.resolution_target_microseconds IS DISTINCT FROM OLD.resolution_target_microseconds OR NEW.acknowledgement_due_at IS DISTINCT FROM OLD.acknowledgement_due_at OR NEW.resolution_due_at IS DISTINCT FROM OLD.resolution_due_at THEN RAISE EXCEPTION 'incident governed snapshot is immutable' USING ERRCODE='23514';END IF;
 IF NEW.status=OLD.status AND NEW.acknowledged_by_user_id IS NOT DISTINCT FROM OLD.acknowledged_by_user_id AND NEW.acknowledged_at IS NOT DISTINCT FROM OLD.acknowledged_at AND NEW.resolved_at IS NOT DISTINCT FROM OLD.resolved_at AND NEW.closed_at IS NOT DISTINCT FROM OLD.closed_at AND NEW.assigned_user_id IS DISTINCT FROM OLD.assigned_user_id AND NEW.status<>'closed' THEN
   IF NEW.assigned_user_id IS NOT NULL AND NOT incident_actor_may_write(NEW.assigned_user_id,OLD.organization_id,OLD.territory_id,clock_timestamp()) THEN RAISE EXCEPTION 'incident assignee is unauthorized' USING ERRCODE='23514';END IF;RETURN NEW;
 END IF;
 IF OLD.status='open' AND NEW.status='acknowledged' AND NEW.acknowledged_by_user_id=actor_id AND NEW.assigned_user_id IS NOT DISTINCT FROM OLD.assigned_user_id THEN NEW.acknowledged_at:=clock_timestamp();RETURN NEW;END IF;
 IF OLD.status='acknowledged' AND NEW.status='investigating' AND NEW.assigned_user_id IS NOT DISTINCT FROM OLD.assigned_user_id THEN RETURN NEW;END IF;
 SELECT bool_and(a.automatic_state='cleared') INTO all_cleared FROM incident_alarm_links l JOIN alarms a ON a.id=l.alarm_id WHERE l.incident_id=OLD.id;
 IF OLD.status='investigating' AND NEW.status='resolved' AND all_cleared AND NEW.assigned_user_id IS NOT DISTINCT FROM OLD.assigned_user_id THEN NEW.resolved_at:=clock_timestamp();RETURN NEW;END IF;
 IF OLD.status='resolved' AND NEW.status='closed' AND all_cleared AND NEW.assigned_user_id IS NOT DISTINCT FROM OLD.assigned_user_id THEN NEW.closed_at:=clock_timestamp();RETURN NEW;END IF;
 RAISE EXCEPTION 'incident lifecycle transition is invalid' USING ERRCODE='23514';
END $$;
CREATE OR REPLACE FUNCTION incident_link_validate() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE i incidents%ROWTYPE;a alarms%ROWTYPE;BEGIN PERFORM pg_advisory_xact_lock(hashtext(NEW.alarm_id::text));SELECT * INTO STRICT i FROM incidents WHERE id=NEW.incident_id;SELECT * INTO STRICT a FROM alarms WHERE id=NEW.alarm_id;NEW.linked_at:=clock_timestamp();IF i.status IN('resolved','closed') OR a.organization_id<>i.organization_id OR a.territory_id<>i.territory_id OR NOT incident_actor_may_write(NEW.linked_by_user_id,i.organization_id,i.territory_id,NEW.linked_at) THEN RAISE EXCEPTION 'incident alarm link is invalid' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE OR REPLACE FUNCTION incident_history_complete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM incident_alarm_links WHERE incident_id=NEW.id AND alarm_id=NEW.primary_alarm_id) OR NOT EXISTS(SELECT 1 FROM incident_timeline WHERE incident_id=NEW.id AND kind='created') OR (NEW.status IN('acknowledged','investigating','resolved','closed') AND NOT EXISTS(SELECT 1 FROM incident_timeline WHERE incident_id=NEW.id AND kind='acknowledged')) OR (NEW.status IN('investigating','resolved','closed') AND NOT EXISTS(SELECT 1 FROM incident_timeline WHERE incident_id=NEW.id AND kind='investigating')) OR (NEW.status IN('resolved','closed') AND NOT EXISTS(SELECT 1 FROM incident_timeline WHERE incident_id=NEW.id AND kind='resolved')) OR (NEW.status='closed' AND NOT EXISTS(SELECT 1 FROM incident_timeline WHERE incident_id=NEW.id AND kind='closed')) THEN RAISE EXCEPTION 'incident history is incomplete' USING ERRCODE='23514';END IF;RETURN NULL;END $$;
CREATE OR REPLACE FUNCTION incident_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'incident history is immutable' USING ERRCODE='23514';END $$;
CREATE OR REPLACE FUNCTION incident_audit() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE action_value audit_event_action;resource_value audit_event_resource;actor_id uuid;reason_value text;request_value text;incident_row incidents%ROWTYPE;BEGIN IF TG_TABLE_NAME='escalation_policies' THEN action_value:='escalation_policy.created';resource_value:='escalation_policy';actor_id:=NEW.created_by_user_id;reason_value:=NEW.creation_reason;request_value:=NEW.created_request_id;INSERT INTO audit_events(organization_id,territory_id,actor_user_id,actor_organization_id,action,resource,resource_id,old_state,new_state,reason,request_id,data_classification,provenance) SELECT NEW.organization_id,NEW.territory_id,actor_id,u.organization_id,action_value,resource_value,NEW.id,NULL,to_jsonb(NEW),reason_value,request_value,'synthetic',NEW.provenance FROM identity_users u WHERE u.id=actor_id;RETURN NEW;END IF;IF TG_TABLE_NAME='incident_timeline' THEN SELECT * INTO STRICT incident_row FROM incidents WHERE id=NEW.incident_id;action_value:=('incident.'||CASE NEW.kind WHEN 'alarm_linked' THEN 'alarm_linked' WHEN 'corrective_action' THEN 'corrective_action' ELSE NEW.kind END)::audit_event_action;INSERT INTO audit_events(organization_id,territory_id,actor_user_id,actor_organization_id,action,resource,resource_id,old_state,new_state,reason,request_id,data_classification,provenance) SELECT incident_row.organization_id,incident_row.territory_id,NEW.actor_user_id,u.organization_id,action_value,'incident',incident_row.id,NULL,to_jsonb(NEW),NEW.reason,NEW.request_id,'synthetic','synthetic incident workflow' FROM identity_users u WHERE u.id=NEW.actor_user_id;RETURN NEW;END IF;RETURN NEW;END $$;
CREATE OR REPLACE FUNCTION escalation_policy_version_audit() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE p escalation_policies%ROWTYPE;actor uuid;action_value audit_event_action;reason_value text;request_value text;BEGIN SELECT * INTO STRICT p FROM escalation_policies WHERE id=NEW.policy_id;actor:=CASE WHEN TG_OP='INSERT' THEN NEW.requested_by_user_id ELSE NEW.approved_by_user_id END;action_value:=CASE WHEN TG_OP='INSERT' THEN 'escalation_policy_version.requested'::audit_event_action ELSE 'escalation_policy_version.approved'::audit_event_action END;reason_value:=CASE WHEN TG_OP='INSERT' THEN NEW.request_reason ELSE NEW.approval_reason END;request_value:=CASE WHEN TG_OP='INSERT' THEN NEW.requested_request_id ELSE NEW.approved_request_id END;INSERT INTO audit_events(organization_id,territory_id,actor_user_id,actor_organization_id,action,resource,resource_id,old_state,new_state,reason,request_id,data_classification,provenance) SELECT p.organization_id,p.territory_id,actor,u.organization_id,action_value,'escalation_policy',NEW.id,CASE WHEN TG_OP='INSERT' THEN NULL ELSE to_jsonb(OLD) END,to_jsonb(NEW),reason_value,request_value,'synthetic',p.provenance FROM identity_users u WHERE u.id=actor;RETURN NEW;END $$;
DROP TRIGGER IF EXISTS escalation_policies_validate ON escalation_policies;CREATE TRIGGER escalation_policies_validate BEFORE INSERT ON escalation_policies FOR EACH ROW EXECUTE FUNCTION escalation_policy_validate();
DROP TRIGGER IF EXISTS escalation_policies_immutable ON escalation_policies;CREATE TRIGGER escalation_policies_immutable BEFORE UPDATE OR DELETE ON escalation_policies FOR EACH ROW EXECUTE FUNCTION incident_immutable();
DROP TRIGGER IF EXISTS escalation_policy_versions_validate ON escalation_policy_versions;CREATE TRIGGER escalation_policy_versions_validate BEFORE INSERT ON escalation_policy_versions FOR EACH ROW EXECUTE FUNCTION escalation_policy_version_validate();
DROP TRIGGER IF EXISTS escalation_policy_versions_update ON escalation_policy_versions;CREATE TRIGGER escalation_policy_versions_update BEFORE UPDATE ON escalation_policy_versions FOR EACH ROW EXECUTE FUNCTION escalation_policy_version_update_validate();
DROP TRIGGER IF EXISTS escalation_policy_versions_delete ON escalation_policy_versions;CREATE TRIGGER escalation_policy_versions_delete BEFORE DELETE ON escalation_policy_versions FOR EACH ROW EXECUTE FUNCTION incident_immutable();
DROP TRIGGER IF EXISTS incidents_validate ON incidents;CREATE TRIGGER incidents_validate BEFORE INSERT ON incidents FOR EACH ROW EXECUTE FUNCTION incident_validate();
DROP TRIGGER IF EXISTS incidents_update ON incidents;CREATE TRIGGER incidents_update BEFORE UPDATE ON incidents FOR EACH ROW EXECUTE FUNCTION incident_update_validate();
DROP TRIGGER IF EXISTS incidents_delete ON incidents;CREATE TRIGGER incidents_delete BEFORE DELETE ON incidents FOR EACH ROW EXECUTE FUNCTION incident_immutable();
DROP TRIGGER IF EXISTS incident_links_validate ON incident_alarm_links;CREATE TRIGGER incident_links_validate BEFORE INSERT ON incident_alarm_links FOR EACH ROW EXECUTE FUNCTION incident_link_validate();
DROP TRIGGER IF EXISTS incident_links_immutable ON incident_alarm_links;CREATE TRIGGER incident_links_immutable BEFORE UPDATE OR DELETE ON incident_alarm_links FOR EACH ROW EXECUTE FUNCTION incident_immutable();
DROP TRIGGER IF EXISTS incident_timeline_validate_trigger ON incident_timeline;CREATE TRIGGER incident_timeline_validate_trigger BEFORE INSERT ON incident_timeline FOR EACH ROW EXECUTE FUNCTION incident_timeline_validate();
DROP TRIGGER IF EXISTS incident_timeline_immutable ON incident_timeline;CREATE TRIGGER incident_timeline_immutable BEFORE UPDATE OR DELETE ON incident_timeline FOR EACH ROW EXECUTE FUNCTION incident_immutable();
DROP TRIGGER IF EXISTS incident_history_complete_trigger ON incidents;CREATE CONSTRAINT TRIGGER incident_history_complete_trigger AFTER INSERT OR UPDATE ON incidents DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION incident_history_complete();
DROP TRIGGER IF EXISTS escalation_policy_audit_trigger ON escalation_policies;CREATE TRIGGER escalation_policy_audit_trigger AFTER INSERT ON escalation_policies FOR EACH ROW EXECUTE FUNCTION incident_audit();
DROP TRIGGER IF EXISTS escalation_policy_version_audit_trigger ON escalation_policy_versions;CREATE TRIGGER escalation_policy_version_audit_trigger AFTER INSERT OR UPDATE ON escalation_policy_versions FOR EACH ROW EXECUTE FUNCTION escalation_policy_version_audit();
DROP TRIGGER IF EXISTS incident_timeline_audit_trigger ON incident_timeline;CREATE TRIGGER incident_timeline_audit_trigger AFTER INSERT ON incident_timeline FOR EACH ROW EXECUTE FUNCTION incident_audit();
